name: RealCraft
main: io.github.password12004.RealCraft
version: 1.8.7
commands:
   gate:
	description: Creates/Removes a gateway
	usage: /gate [create|destroy|set1|set2|] [x] [y] [z]
	permission: realcraft.gate
	permission-message: You don't have permission to do this command.
   pee:
	description: Relives your call of nature. Ahh…
	usage: /pee
	permission realcraft.pee.pee
	permission-message: You don't have permission to do this command.
   peeMeter:
	description: Toggles The PeeMeter System.
	usage: /peeMeter [true|false] <player>
	permission: realcraft.pee.peeMeter
	permission-message: You don't have permission to do this command.
permissions:

    doorman.*:
        description: Gives access to all doorman commands
        children:
            doorman.kick: true
            doorman.ban: true
            doorman.knock: true
            doorman.denied: false
    doorman.kick:
        description: Allows you to kick a user
        default: op
    doorman.ban:
        description: Allows you to ban a user
        default: op
    doorman.knock:
        description: Knocks on the door!
        default: true
    doorman.denied:
        description: Prevents this user from entering the door
    doorman.bell:
	description: Activates Doorbell sound

    pee.*:
	description: Gives access to ReliefConftrol System.
        children:
		pee.peeMeter
		pee.pee
    pee.pee:
	description: Allows you to Uriniate. Ahhh…
    pee.peeMeter
	description: Allows someone to control peeMeters